# Generated by Django 5.1.2 on 2024-11-05 01:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolPropuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(default='Untitled', max_length=255)),
                ('Descripcion', models.TextField(default='Untitled', max_length=555)),
                ('Zona', models.CharField(default='Untitled', max_length=255)),
                ('Costo', models.CharField(default='Untitled', max_length=255)),
                ('Inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('FechaF', models.DateTimeField(default=django.utils.timezone.now)),
                ('votes_up', models.IntegerField(default=0)),
                ('votes_down', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('administrador', 'Administrador'), ('Ciudadano', 'Ciudadano')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=10)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solpropuesta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'propuesta')},
            },
        ),
    ]
